using System;
using System.Collections.Generic;
using DG.Tweening;
using Managers.Inspection;
using UnityEngine;

namespace Managers.CoreLogic
{
    public class GuestSpawner : MonoBehaviour
    {
        [Header("Spawn Settings")]
        [SerializeField] 
        private Transform _spawnPoint;
        
        [SerializeField] 
        private Transform _counterPoint;
        
        [SerializeField] 
        private Transform _exitPoint;
        
        [SerializeField] 
        private List<GuestObject> _guestPrefabs;

        [Header("References")] 
        [SerializeField]
        private DeskManager _deskManager;

        Dictionary<string, GuestObject> _guestDictionary = new Dictionary<string, GuestObject>();
        
        private GuestObject _currentActiveGuestObject;
        
        public GuestObject CurrentActiveGuestObject => _currentActiveGuestObject;

        private void Awake()
        {
            for (int i = 0; i < _guestPrefabs.Count; i++)
            {
                string autoGeneratedId = "Type_" + (i + 1);

                if (_guestPrefabs[i] != null)
                {
                    _guestDictionary.Add(autoGeneratedId, _guestPrefabs[i]);
                }
            }
        }

        private void Start()
        {
            BombManager.OnBombReleased += _handleOnBombReleased;
        }

        private void OnDestroy()
        {
            BombManager.OnBombReleased -= _handleOnBombReleased;
        }


        private void _handleOnBombReleased()
        {
            _currentActiveGuestObject.ReleaseBomb();
        }

        public void SpawnGuest(string guestId)
        {
            GuestEntry guestData = GuestManager.GetGuest(guestId);
            if (guestData == null) return;

            string prefabType = _getPrefabTypeFromData(guestData.globalData);

            if (_guestDictionary.TryGetValue(prefabType, out GuestObject prefabToSpawn))
            {
                _currentActiveGuestObject = Instantiate(prefabToSpawn, _spawnPoint.position, _spawnPoint.rotation);
                _currentActiveGuestObject.SetIsDangerous(guestData.isDangerous);
                _currentActiveGuestObject.Initialize();

                _currentActiveGuestObject.MoveToCounter(_counterPoint, _onGuestArrivedAtCounter);
            }
            else
            {
                Debug.LogError($"HATA: {prefabType} adında bir prefab Dictionary'de bulunamadı!");
            }
        }

        private void _onGuestArrivedAtCounter()
        {
            _deskManager.SpawnGuestDocuments(ReceptionGameManager.CurrentGuestId);
        }

        public void DismissGuest(bool isApproved, Action onGuestLeftFacility)
        {
            if (_currentActiveGuestObject == null) 
            {
                onGuestLeftFacility?.Invoke();
                return;
            }

            _currentActiveGuestObject.PlayReaction(isApproved);
            Transform correctExitPoint = isApproved ? _exitPoint : _spawnPoint;
    
            DOVirtual.DelayedCall(2.0f, () => 
            {
                if (_currentActiveGuestObject != null)
                {
                    _currentActiveGuestObject.Leave(correctExitPoint, () => 
                    {
                        _currentActiveGuestObject = null;
                        onGuestLeftFacility?.Invoke(); 
                    });
                }
            });
        }

        private string _getPrefabTypeFromData(DocumentFieldData[] fields)
        {
            DocumentFieldData matchedData = Array.Find(fields, f => f.key == "Prefab");
            return matchedData != null ? matchedData.value : "Type_1";
        }
        
    }
    
}
